tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "autojump"
brew "bat"
brew "coreutils"
brew "fd"
brew "fzf"
brew "gh"
brew "gpg"
brew "htop"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "tldr"
brew "zsh"

cask "homebrew/cask-fonts/font-sauce-code-pro-nerd-font"
cask "kitty"
cask "logseq"
